"""
export_crewai.py - Export GitSentinel to native CrewAI Agent definition.
Visa 02: CrewAI (+250 points)
"""
import os
import json
import yaml
from typing import Any, Dict

def export_to_crewai(root_dir: str) -> Dict[str, Any]:
    with open(os.path.join(root_dir, "agent.yaml"), "r", encoding="utf-8") as f:
        manifest = yaml.safe_load(f)
    with open(os.path.join(root_dir, "SOUL.md"), "r", encoding="utf-8") as f:
        soul = f.read()
    with open(os.path.join(root_dir, "RULES.md"), "r", encoding="utf-8") as f:
        rules = f.read()

    crewai_agent_config = {
        "role": "Autonomous Git-native Security & Compliance Gate Worker",
        "goal": "Inspect all Git diffs, PRs, and commits for leaked credentials, vulnerabilities, and policy violations, providing immediate unified patch remediation.",
        "backstory": f"{soul}\n\nStrict Rules of Engagement:\n{rules}",
        "verbose": True,
        "allow_delegation": False,
        "tools": list(manifest.get("tools", [])),
        "passport_metadata": {
            "passport_id": manifest.get("passport", {}).get("id", "aps-sentinel-01"),
            "framework_visa": "crewai",
            "spec_version": manifest.get("spec_version", "0.1.0")
        }
    }

    # Generate a ready-to-run CrewAI python script
    crewai_code = f'''# Generated by GitAgent Exporter for CrewAI
import os
from crewai import Agent

git_sentinel_agent = Agent(
    role="{crewai_agent_config['role']}",
    goal="{crewai_agent_config['goal']}",
    backstory="""{crewai_agent_config['backstory']}""",
    verbose=True,
    allow_delegation=False
)
'''

    out_json = os.path.join(root_dir, "exports", "crewai", "crewai_agent_config.json")
    out_py = os.path.join(root_dir, "exports", "crewai", "crewai_agent.py")
    os.makedirs(os.path.dirname(out_json), exist_ok=True)

    with open(out_json, "w", encoding="utf-8") as f:
        json.dump(crewai_agent_config, f, indent=2)
    with open(out_py, "w", encoding="utf-8") as f:
        f.write(crewai_code)

    return {
        "visa": "VISA 02 - CrewAI",
        "status": "VERIFIED",
        "output_files": [out_json, out_py]
    }

if __name__ == "__main__":
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    result = export_to_crewai(root)
    print(json.dumps(result, indent=2))
